language: php

sudo: false

before_script:
  - composer install
  - php -S localhost:8000 -t tests/

script:
  - vendor/bin/phpunit

matrix:
  include:
    - php: 5.3
      dist: precise

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
